name: Terraform-Infra
on: 
   push:
       branches:
           - main
           - dev
   pull_request: 
       branches:
           - main
           - dev
jobs:
  Terraform_Install:
    name: Terraform Install
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Vatsal-SH/Infra-Todo
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v4
        
    - name: Terraform Init  
      run: terraform init
      
    - name: Terraform Plan
      run: terraform plan
      
    - name: Terraform Apply
      run: terraform apply
    
  
